### ISSUE TITLE
the observations are missing in the graphs. They only show only model simulations

### ISSUE THREAD

**Issue by fbaffie** [NVE/Flood_forecasting#24]
I can't see where the observations are missing. To double check

**Comment by ElinLangsholt** [comment]
The observations are there. The confusing thing was that ODM overlays them. Why are ODM simulations exactly similar to the observations? They are probably not??

**Comment by fbaffie** [comment]
Ok, that probably means that I by mistake extract the observations from ODM and not the model results. I told Zelalem that I was not too sure about the codes (for the html calls) for ODM, especially regarding groundwater status, so I'll double check this.

**Comment by ElinLangsholt** [comment]
You're nottalking about DDD now?

**Comment by fbaffie** [comment]
No, the groundwater is already there for DDD.
We need to have the codes specific to each variable of ODM to be able to
read them via the html REST API interface. I have implemented the function
in NVEDATA but I'm a bit unclear as to which codes represent which variable.

2018-01-16 11:16 GMT+01:00 ElinLangsholt <notifications@github.com>:

**Comment by fbaffie** [comment]
Elin will ask Bard about the possibility to use the database for all models, and organise API Calls for them.
For the moment, I will delete the past data from ODM as it is the same as the observation

**Comment by fbaffie** [comment]
I have fixed this problem on NVEDATA. It should work operationally at the next update of the NVEDATRA package
